### ISSUE TITLE
Autocrafter does not allow hoppers to pull items from dropper.

### ISSUE THREAD

**Issue by MerlinofMines** [andrepl/Autocrafter#4]
Hey, I'm trying to make a cake factory with the autocrafter plugin, but I'm not able to pull empty buckets from the dropper using a hopper.

I looked in your source and the problem is that you treat all InventoryItemMove events as though the dropper initiated the event.  I think you need to refactor the code, or at least put in an exception, in the event that a hopper is pulling items from the hopper.

I guess it's not my place to decide how your autocraft business logic works, but I'd argue that a hopper should be able to pull items from the dropper without the autocrafter interfering.

Thoughts?

Thanks

**Comment by andrepl** [comment]
[Development Build #17](http://mcgitlab.norcode.com:8081/job/Autocrafter/17/com.norcode.bukkit.autocrafter$Autocrafter/) should fix the hopper issue.  If you could test it and let me know I would appreciate it.  I looked into the refactor a bit more but it's not super easy.  I've added an extra comment to indicate the difference between the 2 handlers, if you feel like submitting a pull request to address it I'll gladly merge it (assuming it doesn't break other stuff) otherwise it'll have to wait until I have some free time. I've got a few other plugins that need 1.7 attention first.

**Comment by MerlinofMines** [comment]
Smoke test says that it's working.  Unless I uncover some unforseen issue I'd say this one's closed.  Thanks!
